DROP TABLE IF EXISTS PURCHASE_ORDER;  
CREATE TABLE PURCHASE_ORDER (  
order_id IDENTITY NOT NULL PRIMARY KEY,  
order_name VARCHAR(50) NOT NULL,  
order_price INT(8) NOT NULL,
is_deleted Boolean NOT NULL DEFAULT false,
order_date DATE DEFAULT CURRENT_TIMESTAMP()
);  

DROP TABLE IF EXISTS PRODUCT_ITEM;  
CREATE TABLE PRODUCT_ITEM (  
item_id IDENTITY NOT NULL PRIMARY KEY,  
item_name VARCHAR(50) NOT NULL,  
item_price INT(8) NOT NULL
);  

DROP TABLE IF EXISTS ORDER_ITEM;  
CREATE TABLE ORDER_ITEM (  
id IDENTITY NOT NULL PRIMARY KEY, 
order_id INT(8) NOT NULL, 
item_id INT(8) NOT NULL,
item_quntity INT(8) NOT NULL
);